name: checks
on: [push, pull_request]
jobs:
  checks:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php: ['7.3', '7.4', '8.0', '8.1', '8.2']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
          tools: composer
      - name: Install CMSimple_XH
        run: |
          curl -fsSL -o CMSimple_XH-1.8.zip https://github.com/cmsimple-xh/cmsimple-xh/releases/download/1.8.0/CMSimple_XH-1.8.zip
          unzip -q CMSimple_XH-1.8.zip
      - name: Checkout Video
        uses: actions/checkout@v4
        with:
          path: cmsimplexh/plugins/video
      - name: composer install
        run: cd cmsimplexh/plugins/video && composer install
      - name: phing sniff
        run: cd cmsimplexh/plugins/video && PATH=vendor/bin:$PATH phing sniff
      - name: phing stan
        run: cd cmsimplexh/plugins/video && PATH=vendor/bin:$PATH phing stan
      - name: phing mess
        run: cd cmsimplexh/plugins/video && PATH=vendor/bin:$PATH phing mess
      - name: phing test
        run: cd cmsimplexh/plugins/video && PATH=vendor/bin:$PATH phing test
